#%RAML 1.0
title: dummy-listener-sap-connectivity
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/e736435d-fdfd-48ba-b295-567491252f1d/api # baseUri: localhost:8084/api
mediaType: [ application/xml ]
version: v1

/test:
  get:
    responses:
      200:
        body:
          application/xml:
            example:
              <message>message received succesfully</message>

  post:
    body:
      application/xml:
    responses:
      200:
        body:
            application/xml:
              example:
                <message>message received succesfully</message>